# placebo config
header: "&6&lNiceTablist &f - &7v1.0"
footer: "&6www.niceplugins.net"

tablist:
  # You can use 20 slots in each column of the tab, if you use more than that it won't work!
  left:
    - "&6&lNice Network"
    - ""
    - ""
    - "&fOnline: &6{online}"
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - "&7Discord"
    - "&6dc.niceplugins.net"
    - ""
    - ""
    - ""
  middle:
    - ""
    - ""
    - ""
    - "&fPing: &6{ping}ms"
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - "&7Store"
    - "&6store.niceplugins.net"
    - ""
    - ""
    - ""
  right:
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
  far_right:
    - ""
    - ""
    - ""
    - "&fPlayer: &6{player}"
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - ""
    - "&7Twitter"
    - "&6@NicePluginsMC"
    - ""
    - ""
    - ""

messages:
  help:
    - "&6&lNiceTablist &f- &lHelp Commands"
    - ""
    - "&6/nicetablist &f- &7Shows this help command."
    - "&6/nicetablist reload &f- &7Reloads the config."
    - ""
  reload:
    - "&aWe are reloading the plugin,"
    - "&aplease wait..."
  reloaded:
    - "&aNiceScore reloaded successfully!"
    - "&aThanks for using my plugin!"